// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2_bldp6vlPsP6Z90I4sL15AynZxaN8o',
    appId: '1:431999390141:web:b97b423e8f9ff41c3a02d4',
    messagingSenderId: '431999390141',
    projectId: 'app-fatec-lista-tarefas-701bb',
    authDomain: 'app-fatec-lista-tarefas-701bb.firebaseapp.com',
    storageBucket: 'app-fatec-lista-tarefas-701bb.appspot.com',
    measurementId: 'G-5YRXZPN27R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_iXoaPlHt5HrMsKmOJPoihQDljR8UOY8',
    appId: '1:431999390141:android:f55a6e1073f41adc3a02d4',
    messagingSenderId: '431999390141',
    projectId: 'app-fatec-lista-tarefas-701bb',
    storageBucket: 'app-fatec-lista-tarefas-701bb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC-25hJQYX0ilKmKSFdoFvYljAoWbUin4M',
    appId: '1:431999390141:ios:6d450af4376bec253a02d4',
    messagingSenderId: '431999390141',
    projectId: 'app-fatec-lista-tarefas-701bb',
    storageBucket: 'app-fatec-lista-tarefas-701bb.appspot.com',
    iosBundleId: 'com.example.app08Firebase',
  );
}
